### ISSUE TITLE
A new one

### ISSUE THREAD

**Issue by jendewalt** [zubeio/blank#30]
use strike-through markdown ~~ word ~~, i look at the preview, and the word is indeed stroke through. Then when i go back to edit mode, the markdown codes for strike-through has disappeared

**Comment by 204NoContent** [comment]
When I edit a cards and try to use strike-through markdown ~~word~~, i look at the preview, and the word is indeed stroke through. Then when i go back to edit mode, the markdown codes for strike-through has disappeared.

**Comment by 204NoContent** [comment]
use strike-through markdown ~~ word ~~, i look at the preview, and the word is indeed stroke through. Then when i go back to edit mode, the markdown codes for strike-through has disapp
